/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* LED */
#define LED_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_0_INBUF_ENABLED 0u
#define LED_0_INIT_DRIVESTATE 0u
#define LED_0_INIT_MUXSEL 0u
#define LED_0_INPUT_SYNC 2u
#define LED_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_0_NUM 1u
#define LED_0_PORT GPIO_PRT1
#define LED_0_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define LED_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_INBUF_ENABLED 0u
#define LED_INIT_DRIVESTATE 0u
#define LED_INIT_MUXSEL 0u
#define LED_INPUT_SYNC 2u
#define LED_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_NUM 1u
#define LED_PORT GPIO_PRT1
#define LED_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Bouton */
#define Bouton_0_DRIVEMODE CY_GPIO_DM_PULLUP
#define Bouton_0_INBUF_ENABLED 1u
#define Bouton_0_INIT_DRIVESTATE 1u
#define Bouton_0_INIT_MUXSEL 0u
#define Bouton_0_INPUT_SYNC 2u
#define Bouton_0_INTERRUPT_MODE CY_GPIO_INTR_BOTH
#define Bouton_0_NUM 4u
#define Bouton_0_PORT GPIO_PRT0
#define Bouton_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Bouton_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Bouton_DRIVEMODE CY_GPIO_DM_PULLUP
#define Bouton_INBUF_ENABLED 1u
#define Bouton_INIT_DRIVESTATE 1u
#define Bouton_INIT_MUXSEL 0u
#define Bouton_INPUT_SYNC 2u
#define Bouton_INTERRUPT_MODE CY_GPIO_INTR_BOTH
#define Bouton_NUM 4u
#define Bouton_PORT GPIO_PRT0
#define Bouton_SLEWRATE CY_GPIO_SLEW_FAST
#define Bouton_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* I2C_1_scl */
#define I2C_1_scl_0_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define I2C_1_scl_0_INBUF_ENABLED 1u
#define I2C_1_scl_0_INIT_DRIVESTATE 1u
#define I2C_1_scl_0_INIT_MUXSEL 19u
#define I2C_1_scl_0_INPUT_SYNC 2u
#define I2C_1_scl_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define I2C_1_scl_0_NUM 0u
#define I2C_1_scl_0_PORT GPIO_PRT5
#define I2C_1_scl_0_SLEWRATE CY_GPIO_SLEW_FAST
#define I2C_1_scl_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define I2C_1_scl_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define I2C_1_scl_INBUF_ENABLED 1u
#define I2C_1_scl_INIT_DRIVESTATE 1u
#define I2C_1_scl_INIT_MUXSEL 19u
#define I2C_1_scl_INPUT_SYNC 2u
#define I2C_1_scl_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define I2C_1_scl_NUM 0u
#define I2C_1_scl_PORT GPIO_PRT5
#define I2C_1_scl_SLEWRATE CY_GPIO_SLEW_FAST
#define I2C_1_scl_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* I2C_1_sda */
#define I2C_1_sda_0_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define I2C_1_sda_0_INBUF_ENABLED 1u
#define I2C_1_sda_0_INIT_DRIVESTATE 1u
#define I2C_1_sda_0_INIT_MUXSEL 19u
#define I2C_1_sda_0_INPUT_SYNC 2u
#define I2C_1_sda_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define I2C_1_sda_0_NUM 1u
#define I2C_1_sda_0_PORT GPIO_PRT5
#define I2C_1_sda_0_SLEWRATE CY_GPIO_SLEW_FAST
#define I2C_1_sda_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define I2C_1_sda_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW
#define I2C_1_sda_INBUF_ENABLED 1u
#define I2C_1_sda_INIT_DRIVESTATE 1u
#define I2C_1_sda_INIT_MUXSEL 19u
#define I2C_1_sda_INPUT_SYNC 2u
#define I2C_1_sda_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define I2C_1_sda_NUM 1u
#define I2C_1_sda_PORT GPIO_PRT5
#define I2C_1_sda_SLEWRATE CY_GPIO_SLEW_FAST
#define I2C_1_sda_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* CapSense_1_Sns */
#define CapSense_1_Sns_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_1_Sns_0_INBUF_ENABLED 0u
#define CapSense_1_Sns_0_INIT_DRIVESTATE 1u
#define CapSense_1_Sns_0_INIT_MUXSEL 0u
#define CapSense_1_Sns_0_INPUT_SYNC 2u
#define CapSense_1_Sns_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_1_Sns_0_NUM 0u
#define CapSense_1_Sns_0_PORT GPIO_PRT7
#define CapSense_1_Sns_0_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_1_Sns_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define CapSense_1_Sns_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_1_Sns_INBUF_ENABLED 0u
#define CapSense_1_Sns_INIT_DRIVESTATE 1u
#define CapSense_1_Sns_INIT_MUXSEL 0u
#define CapSense_1_Sns_INPUT_SYNC 2u
#define CapSense_1_Sns_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_1_Sns_NUM 0u
#define CapSense_1_Sns_PORT GPIO_PRT7
#define CapSense_1_Sns_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_1_Sns_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* CapSense_1_Cmod */
#define CapSense_1_Cmod_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_1_Cmod_0_INBUF_ENABLED 0u
#define CapSense_1_Cmod_0_INIT_DRIVESTATE 1u
#define CapSense_1_Cmod_0_INIT_MUXSEL 0u
#define CapSense_1_Cmod_0_INPUT_SYNC 2u
#define CapSense_1_Cmod_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_1_Cmod_0_NUM 1u
#define CapSense_1_Cmod_0_PORT GPIO_PRT7
#define CapSense_1_Cmod_0_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_1_Cmod_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define CapSense_1_Cmod_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_1_Cmod_INBUF_ENABLED 0u
#define CapSense_1_Cmod_INIT_DRIVESTATE 1u
#define CapSense_1_Cmod_INIT_MUXSEL 0u
#define CapSense_1_Cmod_INPUT_SYNC 2u
#define CapSense_1_Cmod_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_1_Cmod_NUM 1u
#define CapSense_1_Cmod_PORT GPIO_PRT7
#define CapSense_1_Cmod_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_1_Cmod_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
