/*******************************************************************************
* File Name: cyfitter_sysint.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_H
#define INCLUDED_CYFITTER_SYSINT_H
#include "cy_device_headers.h"

/* Bouton_ISR */
#define Bouton_ISR__INTC_CORTEXM4_ASSIGNED 1
#define Bouton_ISR__INTC_CORTEXM4_PRIORITY 7u
#define Bouton_ISR__INTC_NUMBER 0u
#define Bouton_ISR_INTC_CORTEXM4_ASSIGNED 1
#define Bouton_ISR_INTC_CORTEXM4_PRIORITY 7u
#define Bouton_ISR_INTC_NUMBER 0u

/* I2C_1_SCB_IRQ */
#define I2C_1_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define I2C_1_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define I2C_1_SCB_IRQ__INTC_NUMBER 46u
#define I2C_1_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define I2C_1_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define I2C_1_SCB_IRQ_INTC_NUMBER 46u

/* CapSense_1_ISR */
#define CapSense_1_ISR__INTC_CORTEXM4_ASSIGNED 1
#define CapSense_1_ISR__INTC_CORTEXM4_PRIORITY 7u
#define CapSense_1_ISR__INTC_NUMBER 49u
#define CapSense_1_ISR_INTC_CORTEXM4_ASSIGNED 1
#define CapSense_1_ISR_INTC_CORTEXM4_PRIORITY 7u
#define CapSense_1_ISR_INTC_NUMBER 49u

#endif /* INCLUDED_CYFITTER_SYSINT_H */
